### ISSUE TITLE
你好,  请问可以提供下数据格式吗?

### ISSUE THREAD

**Issue by linzhenpeng** [heshenghuan/linear_chain_crf#1]
you said  "As long as the format of given data is correct,this project......"   but you didn't give the format of data
thanks

**Comment by linzhenpeng** [comment]
抱歉   刚开始入门 不太了解 我已经知道格式了   谢谢

**Comment by heshenghuan** [comment]
已更新README文档，当中介绍了数据格式

**Comment by linzhenpeng** [comment]
谢谢
