### ISSUE TITLE
你好  项目好像没有test模块的? 载入训练好的模型,预测没有标记的数据

### ISSUE THREAD

**Issue by linzhenpeng** [heshenghuan/linear_chain_crf#2]
如题, 谢谢

**Comment by linzhenpeng** [comment]
如果把train_steps 设置为0  
restore_model设置为 模型的地址  
但是测试的数据改变后就会报错  
使用原有的测试数据 就不会报错,并且可以正常预测

**Comment by heshenghuan** [comment]
当初写程序的时候是一体化设计的，训练时给出测试文件，训练完直接test。
所以就没有写restore_model相关的实现

**Comment by linzhenpeng** [comment]
谢谢    说说我测试模块的实现方式 保存训练时的 words2idx,feats2idx,label2idx  到文本中, 同时也使用tf的Saver模块保存模型, 预测模块 中先载入 words2idx,feats2idx,label2idx   再 载入模型.  
但是我现在遇到的问题是  不知道    l1_regularizer  如何设置(我是新手)....
把它设置到  weights
self.W = tf.get_variable(
                shape=[self.feat_size, self.nb_classes],
                initializer=tf.truncated_normal_initializer(stddev=0.01),
                name='weights'
                ,regularizer=tf.contrib.layers.l1_regularizer(0.1)
            )
上  但是训练后还是没有把没用的权重设置为空

**Comment by heshenghuan** [comment]
@linzhenpeng 为何要设置l1_regularizer呢？我的代码是有l2正则化的，在loss计算的时候利用了tf.nn.l2_loss()计算

**Comment by linzhenpeng** [comment]
这是因为我训练完成的模型最终是在安卓手机上使用的,
训练完之后 我会把权重,偏移,转移矩阵 保存起来
`               ww, bb,tt = sess.run([self.W,self.b, self.transition])
                with cs.open(FLAGS.model_save_dir + "traindata", 'a') as wt:
                    wt.write("#data_transition#\n")
                    for i_1 in range(len(tt)):
                        for i_2 in range(len(tt[i_1])):
                            wt.write("%.20f" % float(tt[i_1][i_2]) + "\n")
                    wt.write("#data_bias#\n")
                    for i_1 in range(len(bb)):
                        wt.write("%.20f" % float(bb[i_1]) + "\n")
                    wt.write("#data_weights#\n")
                    for i_1 in range(len(ww)):
                        for i_2 in range(len(ww[i_1])):
                            wt.write("%.20f" % float(ww[i_1][i_2]) + "\n")`
只使用 l2  会减低一些没用特征的权重值(权值衰减),但是模型还是很大,特征和权重值还是很多.
我需要使用l1  来去掉没用的特征,实现稀疏矩阵,从而选择特征.简化模型,. 
就如同  CRF++,或者wapiti   训练CRF模型一样.
可以看看 这个博客: [http://blog.csdn.net/zouxy09/article/details/24971995](http://blog.csdn.net/zouxy09/article/details/24971995)

**Comment by heshenghuan** [comment]
@linzhenpeng 抱歉我并没有考虑过这个问题，而且我去查看API好像也没有类似tf.nn.l2_loss()的l1_loss版本。
我的单纯CRF的权重的shape = [self.feat_size, self.nb_classes]，并且我是采用了lookup+reduce_sum的形式来避免稀疏矩阵运算的，可能这导致了regularizer无效。

可以试试--feat_thresh这个参数，它会把出现次数小于某个值的特征删去。
