### ISSUE TITLE
对embcrf模型的调用缺少一个参数

### ISSUE THREAD

**Issue by shuaihuaiyi** [heshenghuan/linear_chain_crf#5]
https://github.com/heshenghuan/linear_chain_crf/blob/5c47fb531d558d6b740d8409b9ee2bc797fc43ff/emb_crf_tagger.py#L218

缺少了window参数

**Comment by heshenghuan** [comment]
https://github.com/heshenghuan/linear_chain_crf/blob/5c47fb531d558d6b740d8409b9ee2bc797fc43ff/emb_crf_tagger.py#L260

使用的是混合模板(HybridTemplate)定义的，不需要再给出window参数。

**Comment by shuaihuaiyi** [comment]
这是test函数中的，这样的写法会把`FLAGS.l2_reg`做为window参数传递进去，导致向量shape定义时出现小数从而报错。至少我使用tf1.6+py3.6跑的时候是不能正常运行的，您可以在自己的环境下测试一下

**Comment by heshenghuan** [comment]
抱歉，之前没注意到这个问题，已经修复了。
