### ISSUE TITLE
写入结果文件时使用了错误的数据结构

### ISSUE THREAD

**Issue by shuaihuaiyi** [heshenghuan/linear_chain_crf#7]
https://github.com/heshenghuan/linear_chain_crf/blob/5c47fb531d558d6b740d8409b9ee2bc797fc43ff/emb_crf_tagger.py#L230

这一行中的test_sentcs是一个三维数组，函数需要的是一个二维数组。这个数组把单个单词也放到了一个列表中，导致维度增加

**Comment by heshenghuan** [comment]
已修复。
