### ISSUE TITLE
加入embedding特征后性能反而下降？

### ISSUE THREAD

**Issue by shuaihuaiyi** [heshenghuan/linear_chain_crf#8]
实验发现其它条件都完全相同的情况下，加入embedding特征后模型性能反而比不加embedding要差，您看这是为什么啊？

**Comment by heshenghuan** [comment]
这很正常，有的任务并不是加上embedding就一定会更好，或者说在同样参数设置下一定会更好。

这和任务的实际情况有关，不同语料训练的embedding也会产生很大的影响。具体实验结果是需要通过调参得到的。
